# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='pubish_time',
        ),
    ]
